"""
Data models for the intervention system.
Provides type safety and validation using Pydantic.
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime


class TestCase(BaseModel):
    """Represents a test case with vehicles, riders, and expected outcome."""
    vehicles: List[Dict[str, Any]]
    riders: List[Dict[str, Any]]
    expected_outcome: str


class Requirement(BaseModel):
    """Represents a requirement surfaced during the intervention."""
    requirement_text: str
    generalization: Optional[str] = None
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)


class InterventionState(BaseModel):
    """Current state of the intervention session."""
    session_id: str
    phase: str = "charter_construction"  # charter_construction | test_execution | requirement_synthesis
    dimensions_identified: List[str] = Field(default_factory=list)
    dimensions_pending: List[str] = Field(default_factory=list)
    requirements_surfaced: List[Requirement] = Field(default_factory=list)
    confusion_level: int = Field(default=0, ge=0, le=10)
    tests_executed: List[Dict[str, Any]] = Field(default_factory=list)
    message_count: int = 0
    premature_test_attempts: int = 0
    predictions_skipped: int = 0
    last_transition: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "session_id": self.session_id,
            "phase": self.phase,
            "dimensions_identified": self.dimensions_identified,
            "dimensions_pending": self.dimensions_pending,
            "requirements_surfaced": [
                {
                    "requirement_text": r.requirement_text,
                    "generalization": r.generalization,
                    "confidence": r.confidence
                }
                for r in self.requirements_surfaced
            ],
            "confusion_level": self.confusion_level,
            "tests_executed": self.tests_executed,
            "message_count": self.message_count,
            "premature_test_attempts": self.premature_test_attempts,
            "predictions_skipped": self.predictions_skipped,
            "last_transition": self.last_transition
        }


class MessageAnalysis(BaseModel):
    """Analysis of user message intent using Claude."""
    proposes_test: bool = False
    includes_prediction: bool = False
    attempts_explanation: bool = False
    suggests_dimension: bool = False
    suggests_generalization: bool = False
    test_case: Optional[TestCase] = None
    dimension_mentioned: Optional[str] = None
    explanation_text: Optional[str] = None
    generalization_text: Optional[str] = None


class Action(BaseModel):
    """Represents an action to take based on transition rule."""
    rule_name: str
    alex_response_directive: str
    example: str
    priority: int = 5
    should_execute_test: bool = False
    should_save_requirement: bool = False
    confusion_delta: int = 0
    phase_transition: Optional[str] = None


class AlexResponse(BaseModel):
    """Response generated by Claude as Alex."""
    message: str
    confusion_delta: int = 0
    requirement_crystallized: Optional[Requirement] = None
    test_to_execute: Optional[TestCase] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class TestResult(BaseModel):
    """Result of executing a test case."""
    test_case: TestCase
    user_prediction: Optional[str] = None
    actual_outcome: str
    passed: bool
    bugs_triggered: List[str] = Field(default_factory=list)
    simulation_results: Dict[str, Any] = Field(default_factory=dict)


class Message(BaseModel):
    """Represents a single conversation message."""
    role: str  # 'user' | 'alex' | 'system'
    content: str
    timestamp: datetime = Field(default_factory=datetime.now)
    confusion_level: Optional[int] = None
    transition_rule_fired: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)
